import os
from dotenv import load_dotenv
import psycopg

load_dotenv()
url = os.getenv('DATABASE_URL').replace('+psycopg', '')
conn = psycopg.connect(url)
cur = conn.cursor()
cur.execute('SELECT column_name, is_nullable FROM information_schema.columns WHERE table_name=%s ORDER BY ordinal_position', ('auth_user',))
print(cur.fetchall())
cur.execute('ALTER TABLE auth_user ALTER COLUMN "User_id" ADD GENERATED BY DEFAULT AS IDENTITY')
conn.commit()
print('identity-added')
conn.close()
