"""removed Username

Revision ID: 1aa2709c7eef
Revises: b0a62d511299
Create Date: 2026-07-06 23:40:24.431236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1aa2709c7eef'
down_revision: Union[str, Sequence[str], None] = 'b0a62d511299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('auth_user_username_key'), 'auth_user', type_='unique')
    op.drop_column('auth_user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('auth_user_username_key'), 'auth_user', ['username'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
