""" Added username and hashed password

Revision ID: 428be51e6a72
Revises: 1aa2709c7eef
Create Date: 2026-07-07 11:05:07.752351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428be51e6a72'
down_revision: Union[str, Sequence[str], None] = '1aa2709c7eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('User_id', sa.Integer(), nullable=False))
    op.add_column('auth_user', sa.Column('Username', sa.String(), nullable=False))
    op.add_column('auth_user', sa.Column('password', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'auth_user', ['Username'])
    op.drop_column('auth_user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('user_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'auth_user', type_='unique')
    op.drop_column('auth_user', 'password')
    op.drop_column('auth_user', 'Username')
    op.drop_column('auth_user', 'User_id')
    # ### end Alembic commands ###
