"""Dropped First Name and Last Name

Revision ID: 72f1c9673925
Revises: 428be51e6a72
Create Date: 2026-07-07 14:19:19.397530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72f1c9673925'
down_revision: Union[str, Sequence[str], None] = '428be51e6a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'First_name')
    op.drop_column('auth_user', 'Last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('Last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('auth_user', sa.Column('First_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
