"""init

Revision ID: b0a62d511299
Revises: 
Create Date: 2026-07-06 23:26:51.203452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0a62d511299'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('First_name', sa.String(), nullable=False),
    sa.Column('Last_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_table('books')
    op.alter_column('BOOK_TABLE', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('BOOK_TABLE', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('BOOK_TABLE', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('BOOK_TABLE', 'published_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               nullable=False)
    op.alter_column('BOOK_TABLE', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('BOOK_TABLE', 'language',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('BOOK_TABLE', 'language',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('BOOK_TABLE', 'page_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('BOOK_TABLE', 'published_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('BOOK_TABLE', 'publisher',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('BOOK_TABLE', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('BOOK_TABLE', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('published_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('books_pkey'))
    )
    op.create_index(op.f('ix_books_id'), 'books', ['id'], unique=False)
    op.drop_table('auth_user')
    # ### end Alembic commands ###
